List<String> suggestions = [
  'Avatar',
  'Titanic',
  'Star Wars: Episode VII - The Force Awakens',
  'Avengers: Endgame',
  'Avatar 2',
  'Vikram',
  'Boo',
  'Apple',
  'Banana',
  'Cherry',
  'Date',
  'Grapes',
  // Add more movie names here...
  "Avatar 4",
  "The Batman",
  "Indiana Jones 5",
  "Black Panther: Wakanda Forever",
  "The Flash",
  "Guardians of the Galaxy Vol. 3",
  "Jurassic World: Dominion",
  "Mission: Impossible 7",
  "Avatar 5",
  "Fantastic Beasts 4",
  "Avatar 2",
  "The Flashpoint Paradox",
  "Aquaman 2",
  "John Wick: Chapter 4",
  "Ant-Man and The Wasp: Quantumania",
  "Thor: Love and Thunder",
  "Doctor Strange in the Multiverse of", "Madness",
  "The Marvels",
  "The Flash: Flashpoint",
  "Indiana Jones 5",
  "Shazam! Fury of the Gods",
  "Sherlock Holmes 3",
  "Minecraft: The Movie",
  "Space Jam: A New Legacy",
  "Fast & Furious 10",
  "Downton Abbey 2",
  "The Expendables 4",
  "The Chronicles of Narnia: The Silver Chair",
  "Minecraft: The Movie",
  "Puss in Boots: The Last Wish",
];
